/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.samford.willharper.fun;

import edu.samford.willharper.stacksandqueues.ListQueue;
import edu.samford.willharper.stacksandqueues.ListStack;
import edu.samford.willharper.stacksandqueues.Queue;
import edu.samford.willharper.stacksandqueues.Stack;
import javax.swing.DefaultListModel;

/**
 *
 * @author user
 */
public class StackQueueGUI extends javax.swing.JFrame {

    protected Stack<String> theStack = new ListStack<>();
    protected Queue<String> theQueue = new ListQueue<>();

    /**
     * Creates new form StackQueueGUI
     */
    public StackQueueGUI() {
        initComponents();
        jLabelData.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextNewItem = new javax.swing.JTextField();
        jButtonPush = new javax.swing.JButton();
        jButtonEnqueue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListStack = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListQueue = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jButtonPop = new javax.swing.JButton();
        jButtonTop = new javax.swing.JButton();
        jButtonDequeue = new javax.swing.JButton();
        jButtonFront = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("New Data Item:");

        jLabel2.setText("Stack");

        jLabel3.setText("Queue");

        jTextNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNewItemActionPerformed(evt);
            }
        });

        jButtonPush.setText("Push");
        jButtonPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPushActionPerformed(evt);
            }
        });

        jButtonEnqueue.setText("Enqueue");
        jButtonEnqueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnqueueActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListStack);

        jScrollPane2.setViewportView(jListQueue);

        jLabel4.setText("Top");

        jLabel5.setText("Rear");

        jLabel6.setText("Front");

        jLabel77.setText("Retrieved Data:");

        jLabel8.setText("Stack");

        jLabel9.setText("Queue");

        jLabelData.setText("[RETRIEVED DATA]");

        jButtonPop.setText("Pop");
        jButtonPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPopActionPerformed(evt);
            }
        });

        jButtonTop.setText("Top");
        jButtonTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTopActionPerformed(evt);
            }
        });

        jButtonDequeue.setText("Dequeue");
        jButtonDequeue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDequeueActionPerformed(evt);
            }
        });

        jButtonFront.setText("Front");
        jButtonFront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrontActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel77)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPop, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonTop, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelData)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPush, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonDequeue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonFront, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonEnqueue))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jButtonPush))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jButtonEnqueue)))
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel77)
                            .addComponent(jLabelData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPop)
                            .addComponent(jButtonTop)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDequeue)
                            .addComponent(jButtonFront)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPopActionPerformed
        // TODO add your handling code here:
        if(!theStack.isEmpty()){
            String item = theStack.pop();
            jLabelData.setText(item);
        }else{
            jLabelData.setText("THE STACK IS EMPTY!");
        }
        //disable the pop and top buttons if stack is empty
        if(theStack.isEmpty()){
            jButtonPop.setEnabled(false);
            jButtonTop.setEnabled(false);
        }
        displayStack();
    }//GEN-LAST:event_jButtonPopActionPerformed

    private void jButtonPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPushActionPerformed
        // TODO add your handling code here:
        theStack.push(jTextNewItem.getText());
        jButtonPop.setEnabled(true);
        jButtonTop.setEnabled(true);
        displayStack();
        jTextNewItem.requestFocus();
        jTextNewItem.selectAll();
    }//GEN-LAST:event_jButtonPushActionPerformed

    private void jButtonEnqueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnqueueActionPerformed
        // TODO add your handling code here:
        theQueue.enqueue(jTextNewItem.getText());
        jButtonDequeue.setEnabled(true);
        jButtonFront.setEnabled(true); //ctr + shift + down arrow copies a line down or highlight two or three lines to do that
        displayQueue();
    }//GEN-LAST:event_jButtonEnqueueActionPerformed

    private void jButtonTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTopActionPerformed
        // TODO add your handling code here:
        if(!theStack.isEmpty()){
            String item = theStack.top();
            jLabelData.setText(item);
        }else{
            jLabelData.setText("THE STACK IS EMPTY!");
        }
    }//GEN-LAST:event_jButtonTopActionPerformed

    private void jTextNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNewItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewItemActionPerformed

    private void jButtonDequeueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDequeueActionPerformed
        // TODO add your handling code here:
        if(!theQueue.isEmpty()){
            String item = theQueue.dequeue();
            jLabelData.setText(item);
        }else{
            jLabelData.setText("THE QUEUE IS EMPTY!");
        }
        //disable the dequeue and front buttons if stack is empty
        if(theQueue.isEmpty()){
            jButtonDequeue.setEnabled(false);
            jButtonFront.setEnabled(false);
        }
        displayQueue();
    }//GEN-LAST:event_jButtonDequeueActionPerformed

    private void jButtonFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrontActionPerformed
        // TODO add your handling code here:
        if(!theQueue.isEmpty()){
            String item = theQueue.front();
            jLabelData.setText(item);
        }else{
            jLabelData.setText("THE QUEUE IS EMPTY!");
        }
    }//GEN-LAST:event_jButtonFrontActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StackQueueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StackQueueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StackQueueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StackQueueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StackQueueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDequeue;
    private javax.swing.JButton jButtonEnqueue;
    private javax.swing.JButton jButtonFront;
    private javax.swing.JButton jButtonPop;
    private javax.swing.JButton jButtonPush;
    private javax.swing.JButton jButtonTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JList<String> jListQueue;
    private javax.swing.JList<String> jListStack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextNewItem;
    // End of variables declaration//GEN-END:variables

    private void displayStack() {

        String theStackStr = theStack.toString();
        //removes []
        theStackStr = theStackStr.substring(1, theStackStr.length() - 1);
        //splits based on the comma
        String stackitems[] = theStackStr.split(",");
        //replaces new model because for some reason it wasn't working
        DefaultListModel demoList = new DefaultListModel();
        for (int i = stackitems.length - 1; i >= 0; i--) {
            String stackitem = stackitems[i];
            demoList.addElement(stackitem);
        }
        jListStack.setModel(demoList);
    }

    private void displayQueue() {
        //the current queue contents
        String theQueueStr = theQueue.toString();
        //removes []
        theQueueStr = theQueueStr.substring(1, theQueueStr.length() - 1);
        //replaces new model because for some reason it wasn't working
        DefaultListModel demoList = new DefaultListModel();
        demoList.addElement(theQueueStr);
        jListQueue.setModel(demoList);
    }

}
